#!/usr/bin/env python
'''
start_controller - Run the controller.

Author: Martin Norbury
August 2012
'''
from optparse import OptionParser

from adaptive_scheduler import log
from adaptive_scheduler import controller

# Module logger
logger = log.create_logger('main')

if __name__ == '__main__':
    logger.info("Starting application")

    # Parse the command line arguments
    parser = OptionParser(description="Scheduler controller")
    parser.add_option("-i", "--interval", dest="interval",
                      help="Polling interval (s)",
                      default=10,
                      type="int")
    options, args = parser.parse_args()

    # Run controller
    controller.run_controller(options.interval)

