name: Build

on:
  # Run this workflow for pushes on all branches
  push:
    branches:
      - '**'
  # Run this workflow when a tag or branch is created
  create:
  # Run this workflow for pull requests
  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip 'poetry>=1.1,<1.2'
        pip install "$(poetry export --without-hashes | grep numpy)" # pyslalib nastiness
        poetry install
        # install our wheel with GLPK support
        # poetry doesn't support custom wheels too well, so just use pip
        poetry run pip install -r ortools-glpk-reqs.txt
    - name: Run tests
      run: poetry run coverage run --source adaptive_scheduler -m pytest --ignore=tests/requires_third_party/test_fullscheduler_gurobi.py -rA
    - name: Generate and send coveralls report
      run: |
        pip install coveralls
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
